SchoolManagement/Models/Examen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Models
{
    public class Examen
    {
        [Display(Name = "Numero d'Examen")]
        public int Id { get; set; }

        [Required]      
        public string  TypeExamen { get; set; }

        [Required]
        [Display(Name = "Date d'Examen")]
        [DataType(DataType.Date)] 
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]

        public DateTime ? DateExam { get; set; }

        public virtual Classe Classe { get; set; }

        [Display(Name = "Nom de la Classe")]
        public virtual int? ClasseId { get; set; }

        public virtual Module Module { get; set; }

        [Display(Name = "Nom du Module")]
        public virtual int? ModuleId { get; set; }

        public  ICollection<Etudiant> Etudiants { get; set; }
    }

    
}

SchoolManagement/Controllers/ExamenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class ExamenController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Examen
        public ActionResult Index()
        {
            var examens = db.examens.Include(e => e.Classe).Include(e => e.Module);
            return View(examens.ToList());
        }

        // GET: Examen/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Examen examen = db.examens.Find(id);
            if (examen == null)
            {
                return HttpNotFound();
            }
            return View(examen);
        }

        // GET: Examen/Create
        public ActionResult Create()
        {
            ViewBag.ClasseId = new SelectList(db.classes, "Id", "Libelle");
            ViewBag.ModuleId = new SelectList(db.Modules, "Id", "Libelle");
            return View();
        }

        // POST: Examen/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TypeExamen,DateExam,ClasseId,ModuleId")] Examen examen)
        {
            if (ModelState.IsValid)
            {
                db.examens.Add(examen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClasseId = new SelectList(db.classes, "Id", "Libelle", examen.ClasseId);
            ViewBag.ModuleId = new SelectList(db.Modules, "Id", "Libelle", examen.ModuleId);
            return View(examen);
        }

        // GET: Examen/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Examen examen = db.examens.Find(id);
            if (examen == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClasseId = new SelectList(db.classes, "Id", "Libelle", examen.ClasseId);
            ViewBag.ModuleId = new SelectList(db.Modules, "Id", "Libelle", examen.ModuleId);
            return View(examen);
        }

        // POST: Examen/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TypeExamen,DateExam,ClasseId,ModuleId")] Examen examen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(examen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClasseId = new SelectList(db.classes, "Id", "Libelle", examen.ClasseId);
            ViewBag.ModuleId = new SelectList(db.Modules, "Id", "Libelle", examen.ModuleId);
            return View(examen);
        }

        // GET: Examen/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Examen examen = db.examens.Find(id);
            if (examen == null)
            {
                return HttpNotFound();
            }
            return View(examen);
        }

        // POST: Examen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Examen examen = db.examens.Find(id);
            db.examens.Remove(examen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/Examen/Create.cshtml
@model SchoolManagement.Models.Examen

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Examen</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TypeExamen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="TypeExamen" class="form-control TypeExamen">
                    <option value="Controle 1">Controle 1</option>
                    <option value="Controle 2">Controle 2</option>
                    <option value="Session Normale">Session Normale</option>
                    <option value="Session Rattrapage">Session Rattrapage</option>
                    
                </select>
                @Html.ValidationMessageFor(model => model.TypeExamen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateExam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateExam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateExam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasseId, "Nom de Classe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModuleId, "Nom du Module", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModuleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

SchoolManagement/Views/Examen/Delete.cshtml
@model SchoolManagement.Models.Examen

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Examen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Classe.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classe.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Module.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Module.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeExamen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeExamen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateExam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateExam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolManagement/Views/Examen/Details.cshtml
@model SchoolManagement.Models.Examen

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Examen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Classe.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classe.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Module.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Module.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeExamen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeExamen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateExam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateExam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retour", "Index")
</p>

SchoolManagement/Views/Examen/Edit.cshtml
@model SchoolManagement.Models.Examen

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modification</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Examen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TypeExamen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="TypeExamen" class="form-control TypeExamen">
                    <option value="Controle 1">Controle 1</option>
                    <option value="Controle 2">Controle 2</option>
                    <option value="Session Normale">Session Normale</option>
                    <option value="Session Rattrapage">Session Rattrapage</option>

                </select>
                @Html.ValidationMessageFor(model => model.TypeExamen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateExam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateExam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateExam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasseId, "Nom de Classe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModuleId, "Nom du Module", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModuleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

SchoolManagement/Views/Examen/Index.cshtml
@model IEnumerable<SchoolManagement.Models.Examen>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>La liste de types des examens</h2>

<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("create","Examen")'">Ajouter Examen</button>
</p>
<br />
<table class="table table-hover table-responsive table-bordered" id="examens">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Classe.Libelle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Module.Libelle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeExamen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateExam)
            </th>
            <th>Modifier</th>
            <th>Details</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classe.Libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Module.Libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeExamen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateExam)
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#examens").DataTable();

        });
    </script>
}