SchoolManagement/Models/paiement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Models
{
    public class paiement
    {
        public int Id { get; set; }

        public virtual Etudiant Etudiant { get; set; }

        [Required]
        public virtual string EtudiantId { get; set; }

        [Required]
        public string TypeReglement { get; set; }


        public string TypePaiement { get; set; }

        [Required]
        public byte DureeEnMois  { get; set; }

        [Required]
        public decimal Montant { get; set; }

        [DisplayFormat(DataFormatString ="{0:dd-MM-yyyy}")]
        public DateTime DatePaiment { get; set; }




    }
}

SchoolManagement/Controllers/paiementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class paiementController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: paiement
        public ActionResult Index()
        {
            var paiements = db.Paiements.Include(p => p.Etudiant);
            return View(paiements.ToList());
        }

        // GET: paiement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paiement paiement = db.Paiements.Find(id);
            if (paiement == null)
            {
                return HttpNotFound();
            }
            return View(paiement);
        }

        // GET: paiement/Create
        public ActionResult Create()
        {
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id");
            return View();
        }

        // POST: paiement/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EtudiantId,TypeReglement,TypePaiement,DureeEnMois,Montant,DatePaiment")] paiement paiement)
        {
            if (ModelState.IsValid)
            {
                paiement.DatePaiment = DateTime.Parse(DateTime.Now.ToShortDateString());
                db.Paiements.Add(paiement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", paiement.EtudiantId);
            return View(paiement);
        }

        // GET: paiement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paiement paiement = db.Paiements.Find(id);
            if (paiement == null)
            {
                return HttpNotFound();
            }
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", paiement.EtudiantId);
            return View(paiement);
        }

        // POST: paiement/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EtudiantId,TypeReglement,TypePaiement,DureeEnMois,Montant,DatePaiment")] paiement paiement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paiement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", paiement.EtudiantId);
            return View(paiement);
        }

        // GET: paiement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paiement paiement = db.Paiements.Find(id);
            if (paiement == null)
            {
                return HttpNotFound();
            }
            return View(paiement);
        }

        // POST: paiement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            paiement paiement = db.Paiements.Find(id);
            db.Paiements.Remove(paiement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/paiement/Create.cshtml
@model SchoolManagement.Models.paiement

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>paiement</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EtudiantId, "EtudiantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EtudiantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EtudiantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeReglement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="TypeReglement" class="form-control TypeReglement">                  
                    <option value="Scolarite"> Scolarite</option>
                    <option value="Inscription">Inscription</option>
                    <option value="Autre">Autre</option>    
                </select>
                @Html.ValidationMessageFor(model => model.TypeReglement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypePaiement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="TypePaiement" class="form-control TypePaiement">
                    <option value="Espéce"> Espéce</option>
                    <option value="Chéque">Chéque</option>
                    <option value="banque">banque</option>
                </select>
                @Html.ValidationMessageFor(model => model.TypePaiement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DureeEnMois, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DureeEnMois, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DureeEnMois, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Montant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Montant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Montant, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

SchoolManagement/Views/paiement/Delete.cshtml
@model SchoolManagement.Models.paiement

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>Vous voulez vraiment supprimer ce paiement?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeReglement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeReglement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypePaiement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypePaiement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DureeEnMois)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DureeEnMois)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePaiment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePaiment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

SchoolManagement/Views/paiement/Details.cshtml
@model SchoolManagement.Models.paiement

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>paiement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeReglement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeReglement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypePaiement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypePaiement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DureeEnMois)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DureeEnMois)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePaiment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePaiment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retour  ", "Index")
</p>

SchoolManagement/Views/paiement/Edit.cshtml
@model SchoolManagement.Models.paiement

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modification</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>paiement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EtudiantId, "EtudiantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EtudiantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EtudiantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeReglement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeReglement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeReglement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypePaiement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypePaiement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypePaiement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DureeEnMois, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DureeEnMois, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DureeEnMois, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Montant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Montant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Montant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePaiment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePaiment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePaiment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

SchoolManagement/Views/paiement/Index.cshtml
@model IEnumerable<SchoolManagement.Models.paiement>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>le paiement </h2>
<br />

<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("create","paiement")'">Ajouter Paiement</button>
</p>
<br />
<table class="table table-hover table-responsive table-bordered" id="paiement">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Etudiant.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeReglement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypePaiement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DureeEnMois)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Montant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePaiment)
            </th>
            <th>Modifier</th>
            <th>Details</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Etudiant.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeReglement)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypePaiement)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DureeEnMois)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Montant)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePaiment)
                </td>
                <td>
                    @Html.ActionLink("Modifier", "Edit", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#paiement").DataTable();

        });
    </script>
}