SchoolManagement/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Models
{
    public class Note
    {
        [Display(Name ="Numero de Note")]
        public int  Id { get; set; }
        public virtual Etudiant  Etudiant { get; set; }

        [Required]
        [Display(Name = "Numero d 'Etudiant")]
        public string EtudiantId { get; set; }

        public virtual Examen  Examen { get; set; }

        [Required]
        [Display(Name = "Numero d'Examen")]
        public int ExamenId { get; set; }

        [Required]
        [Display(Name = "Note d'Examen")]
        public float NoteExamen { get; set; }

        public string  Mention  { get; set; }

       


    }
}

SchoolManagement/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class NoteController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Note
        public ActionResult Index()
        {
            var notes = db.Notes.Include(n => n.Etudiant).Include(n => n.Examen);
            return View(notes.ToList());
        }

        // GET: Note/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Note/Create
        public ActionResult Create()
        {
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id");
            ViewBag.ExamenId = new SelectList(db.examens, "Id", "Id");
            return View();
        }

        // POST: Note/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EtudiantId,ExamenId,NoteExamen,Mention")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", note.EtudiantId);
            ViewBag.ExamenId = new SelectList(db.examens, "Id", "Id", note.ExamenId);
            return View(note);
        }

        // GET: Note/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", note.EtudiantId);
            ViewBag.ExamenId = new SelectList(db.examens, "Id", "Id", note.ExamenId);
            return View(note);
        }

        // POST: Note/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EtudiantId,ExamenId,NoteExamen,Mention")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EtudiantId = new SelectList(db.Etudiants, "Id", "Id", note.EtudiantId);
            ViewBag.ExamenId = new SelectList(db.examens, "Id", "Id", note.ExamenId);
            return View(note);
        }

        // GET: Note/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Note/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagement/Views/Note/Create.cshtml
@model SchoolManagement.Models.Note

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Les Notes</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EtudiantId, "Numero d'Etudiant", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EtudiantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EtudiantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExamenId, "Numero d'Examen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExamenId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExamenId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoteExamen, htmlAttributes: new { @class = "control-label col-md-2 note" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoteExamen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoteExamen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mention, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mention, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mention, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            var note = $("#NoteExamen").val();
            $("#NoteExamen").change(function () {
                if ($("#NoteExamen").val() < 0) {
                    alert("la note doit etre superieure a 0");
                    $("#NoteExamen").val("");
                }

            })
            $("#ExamenId").dblclick(function () {

                window.location.href = "https://localhost:44373/Examen";

               
            })
        });
    </script>
}

SchoolManagement/Views/Note/Delete.cshtml
@model SchoolManagement.Models.Note

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Examen.TypeExamen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Examen.TypeExamen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoteExamen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteExamen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mention)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mention)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolManagement/Views/Note/Details.cshtml
@model SchoolManagement.Models.Note

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Prenom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Nom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Etudiant.Classe.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etudiant.Classe.Libelle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Examen.Module.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Examen.Module.Libelle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Examen.TypeExamen)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Examen.TypeExamen)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Examen.DateExam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Examen.DateExam)
        </dd>
 
        <dt>
            @Html.DisplayNameFor(model => model.NoteExamen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteExamen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mention)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mention)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retour", "Index")
</p>

SchoolManagement/Views/Note/Edit.cshtml
@model SchoolManagement.Models.Note

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EtudiantId, "EtudiantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EtudiantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EtudiantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExamenId, "ExamenId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExamenId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExamenId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoteExamen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoteExamen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoteExamen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mention, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mention, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mention, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolManagement/Views/Note/Index.cshtml
@model IEnumerable<SchoolManagement.Models.Note>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>LES NOTES :</h2>
<br />
<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("create","Note")'">Ajouter Note</button>
</p>
<br />
<table class="table table-hover table-responsive table-bordered"id="notes">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Etudiant.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Examen.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoteExamen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mention)
            </th>
            <th>Modifer</th>
            <th>Details</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Etudiant.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Examen.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoteExamen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mention)
                </td>
                <td>
                    @Html.ActionLink("Modifier", "Edit", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#notes").DataTable();

        });
    </script>
}